export const OPEN_MODAL = 'OPEN_MODAL';
export const CLOSE_MODAL = 'CLOSE_MODAL';
export const NAVIGATE_TO_REIGSTER2 = 'NAVIGATE_TO_REIGSTER2';
export const SETUP_DEVICE = 'SETUP_DEVICE';
export const SETUP_ISCONNECTED = 'SETUP_ISCONNECTED';
export const SETUP_TRANSPORT = 'SETUP_TRANSPORT';
export const SETUP_WALLET = 'SETUP_WALLET';
export const SETUP_PAIRED = 'SETUP_PAIRED';
